title: A bit of A and I
description: A blog about our research and projects
theme: minima

plugins:
  - jekyll-feed  # Adds an RSS feed (optional but useful)

# Minima-specific settings
minima:
  social_links:  # Optional: Add social media links to footer
    - { platform: huggingface, user_url: "https://huggingface.co/NECOUDBFM/Jellyfish" }